### ISSUE TITLE
missing entries/box art for some games

### ISSUE THREAD

**Issue by ghost** [antiKk/muOS-Artwork#1]
FC
fire emblem - shadow dragon and the blade of light 
the flintsones - the surprise at dinosaur peak! (no box art?)
ganbare goemon gaiden - the missing golden pipe
ganbarge goemon gaiden 2 - treasure of the world
go go! nekketu hockey club - multi-sport battle 
kid niki 3
the legend of fuma
the mysterious murasame castle
nekketsu! street basket - go for it, dunk heroes!
perman - return the space saucer
perman 2 - down with the secret madou society
samurai pizza cats
twinbee 3 - the aimless demon king

GB
donkey kong land (sgb enhanced) (no box art?)
the frog for whom the bell tolls
pocket bomberman (sgb enhanced)
solarstriker (no box art?)

GBA
fire emblem the binding blade

most of these games are japan translated games, probably why it failed to generate images for them.

note that i only looked through FC, GB, GBA, GBC and SFC

i'd try to fix these myself and submit a pull request, but i don't know my way around skraper.

**Comment by antiKk** [comment]
I'll see what I can do, but it's possible Skraper doesn't have the missing artwork.
Could possibly just use alternate region art.

**Comment by antiKk** [comment]
Added:
the flintsones - the surprise at dinosaur peak! (no box art?)
ganbare goemon gaiden - the missing golden pipe
ganbarge goemon gaiden 2 - treasure of the world
nekketsu! street basket - go for it, dunk heroes!

**Comment by antiKk** [comment]
All FC Artwork added
All GB Artwork added

**Comment by antiKk** [comment]
Missing GBA files added.
New new release created yet.
Files can be downloaded from respective folder.
